config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]

  devise_for :users, path: :user
  
  resources :chats, except: [:index] do
    get :index, to: redirect('/'), on: :collection
  end
  
  resources :messages, only: [:index]
  
  resources :users, only: [] do
    root to: redirect('/')
  end
  
  unauthenticated { root to: redirect('/user/sign_in') }
  authenticated { root to: 'chats#index' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  after_create_commit { BroadcastMessageJob.perform_later(id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :chats
  has_many :messages
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action ->() { gon.current_user_id = current_user.id }, if: :user_signed_in?
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  expose :chat
  respond_to :html, :json
  before_action ->() { gon.chat_id = chat.id }, if: :chat

  def index
    @chats = Chat.all
    respond_with(@chats)
  end

  def show
    respond_with(chat)
  end

  def new
    respond_with(chat)
  end

  def edit
    respond_with(chat)
  end

  def create
    params[:chat][:user_ids].push current_user.id
    
    respond_with(chat) { chat.save }
  end

  def update
    params[:chat][:user_ids].push current_user.id
    
    respond_with(chat) { chat.update(chat_params) }
  end

  def destroy
    respond_with(chat) { chat.destroy }
  end

  private
    def chat_params
      params.require(:chat).permit(:name, user_ids: [])
    end
end
  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :json
  expose :chat
  expose :messages, -> { chat.messages }

  def index
    respond_with messages
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  has_scope :where, type: :hash

  expose(:users) { apply_scopes(User.all) }

  def index
    respond_with users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  def chat_name(chat)
    chat.name.present? ? chat.name : chat.users.where.not(id: current_user.id).pluck(:email).to_sentence
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_form.html.erb
<%= form_for(chat) do |f| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_ids %>
    <%= f.select :user_ids, User.where.not(id: current_user.id).collect { |u| [u.email, u.id] }, {}, multiple: true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat_name(chat) %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<h1><%= chat_name(chat) %></h1>

<%= div_for chat do %>
  <div id="user_typing"></div>
<% end %>

<%= form_for Message.new(chat: chat, user: current_user), url: '#' do |f| %>
  <%= f.text_field :content, data: { behavior: 'speaker' } %>
<% end %>

<%= link_to 'Edit', edit_chat_path(chat) %> |
<%= link_to 'Back', chats_path, data: { turbolinks: false } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= Gon::Base.render_data %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete if user_signed_in? %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>